language: generic

env:
  - PPA=yes
  - PPA=no

install:
  - if [ x"$PPA" == "xyes" ] ; then sudo add-apt-repository ppa:pi-rho/dev -y; fi
  - sudo apt-get update -q
  - sudo apt-get install vim-nox
  - sudo pip install vim-vint
  - git clone https://github.com/thinca/vim-themis
  - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
  - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
  - git clone https://github.com/vim-jp/vital.vim /tmp/vital.vim

before_script:
  - vim --version
  - vint --version

script:
  - vim-themis/bin/themis --runtimepath /tmp/vital.vim --reporter spec
  - vim --cmd "try | helptags doc/ | catch | cquit | endtry" --cmd quit
  - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -e EVL102.l:_=1 -c func_abort=1 autoload/incsearch.vim
  - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -e EVL102.l:_=1 -c func_abort=1 autoload/incsearch
  - vint autoload/incsearch autoload/incsearch.vim plugin
